### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by noraj** [initstring/lyricpass#2]
python 2 is deprecated and the support will be dropped soon so python support would be welcome

**Comment by initstring** [comment]
Hi @noraj ,

Thank you very much for opening these issues. I didn't think anyone actually used this script anymore. I can try to make some time to update it if it is still helpful.
Would you mind telling me what you use it for? 

If you are using it to build password wordlists, a think a general-purpose lyric scraper would be more useful, as I now spend more time maintaining [this project](https://github.com/initstring/passphrase-wordlist), which has a cleanup.py script that can be used to transform the output into a nice wordlist.

Thanks! Trying to figure out how useful old projects of mine are is helpful in determining where to spend my free time, which unfortunately I don't have a lot of at the moment.

**Comment by noraj** [comment]
Yeah I used it to create a lyrics based password wordlist, then I used John the ripper mutation rules so I didn't need to build permutated wordlist.
Also you will be pleased to know that this tool used your script: https://github.com/R3nt0n/bopscrk

**Comment by noraj** [comment]
PS: I'm a BlackArch Linux developer and I added your tool/script in our repository: https://github.com/BlackArch/blackarch/pull/2441/files
PS2: I'm also the Rawsec Inventory maintainer, and I added your script in the cracking category: https://inventory.rawsec.ml/tools.html#lyricpass

If you know better tool than yours for building a lyrics based wordlist let me know.

**Comment by initstring** [comment]
Interesting, thanks for taking the time to provide this info.

I will create a better, updated version of the tool. I wrote it when I was pretty crap at Python and it's really ugly. :)

I'll make it python3 with only standard libraries, to avoid installation problems.

**Comment by initstring** [comment]
OK, I have a re-write mostly complete in a temporary branch here: https://github.com/initstring/lyricpass/tree/2019-rewrite

I still need to:
- add comments
- add exception handling
- add cleaning rules, possibly tunable with user-supplied arguments
- update the readme to be more relevant to the new format

I'll try to work on this over the coming week or two.

Thanks!

**Comment by noraj** [comment]
Awesome, keep me tuned I'll update the BA PKGBUILD when the py3 version will be ready.

**Comment by initstring** [comment]
@noraj This is pretty cleaned up now, I think it is safe to update the reference.

**Comment by noraj** [comment]
I pushed the update on BA https://github.com/BlackArch/blackarch/pull/2459
